title: Viua VM
email: marekjm@ozro.pw
description: Viua VM - Viua virtual machine
title: Viua VM - Viua virtual machine
url: "http://viuavm.org"

repository_url: "https://github.com/marekjm/viuavm"
releases_url: "https://github.com/marekjm/viuavm/releases"
bugs_url: "https://github.com/marekjm/viuavm/issues"
documentation_url: "http://docs.viuavm.org/"
